### ISSUE TITLE
Adding Retry Policy to the HttpClient

### ISSUE THREAD

**Issue by KZeronimo** [tpeczek/HttpClientFactory.Azure.Functions#1]
Thanks for the great example of how to leverage `IHttpClientFactory` in Azure fxns 

I'm trying to tack on a polly retry policy but any config I do to the HttpClient does not seem to be honored

I've changed 

`builder.Services.AddHttpClient();`

to

```
            builder.Services.AddHttpClient<HttpClient>(client => { })
                .AddPolicyHandler(HttpPolicyExtensions
                    .HandleTransientHttpError()
                    .WaitAndRetryAsync(
                        retryCount: 3,
                        sleepDurationProvider: retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt))));
```

What am I missing? Thanks in advance!

**Comment by tpeczek** [comment]
Hi @KZeronimo.

I have never used policy with unnamed or not strongly typed clients and it looks like it's not supported. I would suggest using named client. This would make the `HttpClientFactoryWebJobsStartup` class look like below:

```cs
public class HttpClientFactoryWebJobsStartup : IWebJobsStartup
{
    public void Configure(IWebJobsBuilder builder)
    {
        builder.AddExtension<HttpClientFactoryExtensionConfigProvider>();

        builder.Services.AddHttpClient("HttpClientFactory.Azure.WebJobs.Extensions")
            .AddTransientHttpErrorPolicy(policyBuilder => policyBuilder.WaitAndRetryAsync(
                retryCount: 3,
                sleepDurationProvider: retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt))
            ));

        builder.Services.Configure<HttpClientFactoryOptions>("HttpClientFactory.Azure.WebJobs.Extensions", options => options.SuppressHandlerScope = true);
    }
}
```

And would require one change in `HttpClientFactoryExtensionConfigProvider` class:

```cs
[Extension("HttpClientFactory")]
internal class HttpClientFactoryExtensionConfigProvider : IExtensionConfigProvider
{
    …

    public void Initialize(ExtensionConfigContext context)
    {
        …

        bindingAttributeBindingRule.BindToInput<HttpClient>((httpClientFactoryAttribute) =>
        {
            return _httpClientFactory.CreateClient("HttpClientFactory.Azure.WebJobs.Extensions");
        });
    }
}
```

This approach work correctly for me.

**Comment by KZeronimo** [comment]
@tpeczek - I wondered about the anonymous client - I had tried a simple named client but did not have the named client in the following

`builder.Services.Configure<HttpClientFactoryOptions>("Named.Client", options => options.SuppressHandlerScope = true);`

Adding the named client to the Configure step fixed this up

Thanks again for the example and answering my question 👍

**Comment by tpeczek** [comment]
@KZeronimo You are welcome
